from widgets.canvasViewWidget import CanvasViewWidget
from widgets.settingViewWidget import SettingViewWidget
from widgets.resultViewWidget import ResultViewWidget
from widgets.tabWidget import TabWidget
from widgets.effectItemWidget import EffectItemWidget